#!/bin/sh

# Ensure <data_dir>/plugins exists.
mkdir -p /opt/nomad/data/plugins

# Symlink driver in the plugins directory.
ln -s /usr/bin/nomad-driver-exec2 /opt/nomad/data/plugins/nomad-driver-exec2
