name: Run CI Tests

on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'

jobs:
  run-lint:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-golang@v3
        with:
          version-file: go.mod
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56.2
          skip-cache: true
          args: --timeout=8m
  run-copywrite:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-copywrite@v1.1.2
      - name: verify copywrite headers
        run: |
          copywrite --config .copywrite.hcl headers --spdx "MPL-2.0" --plan
  run-tests:
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-golang@v3
        with:
          version-file: go.mod
      - name: Run Go Test
        run: |
          sudo sed -i 's!Defaults!#Defaults!g' /etc/sudoers
          sudo -E env "PATH=$PATH" make test
permissions:
  contents: read

